[package]
name = "web-style-transformer"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
inline-style-parser = { path = "../inline-style-parser" }
js-sys = "0.3.77"
lazy_static = "1.5.0"
wasm-bindgen = "=0.2.101"

[profile.release]
opt-level = 3
lto = true
