[package]
name = "react-transform"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
convert_case = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
sha-1 = { workspace = true }
swc_core = { workspace = true, features = ["base", "ecma_codegen", "ecma_parser", "ecma_minifier", "ecma_transforms_typescript", "ecma_utils", "ecma_quote", "ecma_transforms_react", "ecma_transforms_optimization", "css_parser", "css_ast", "css_visit", "css_codegen", "__visit", "__testing_transform"] }
swc_plugin_compat = { path = "./crates/swc_plugin_compat" }
swc_plugin_css_scope = { path = "./crates/swc_plugin_css_scope" }
swc_plugin_define_dce = { path = "./crates/swc_plugin_define_dce" }
swc_plugin_directive_dce = { path = "./crates/swc_plugin_directive_dce" }
swc_plugin_dynamic_import = { path = './crates/swc_plugin_dynamic_import' }
swc_plugin_inject = { path = "./crates/swc_plugin_inject" }
swc_plugin_list = { path = "./crates/swc_plugin_list" }
swc_plugin_shake = { path = './crates/swc_plugin_shake' }
swc_plugin_snapshot = { path = "./crates/swc_plugin_snapshot" }
swc_plugin_worklet = { path = "./crates/swc_plugin_worklet" }
swc_plugins_shared = { path = './crates/swc_plugins_shared' }
version-compare = { workspace = true }

[target."cfg(all(target_arch = \"wasm32\", target_os = \"unknown\"))".dependencies.getrandom]
version = "0.3.3"

[build-dependencies]
napi-build = "2.1.3"

[features]
noop = []
