name: Rust

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

# Set minimum permissions to prevent unnecessary access
permissions: {}

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test (${{ matrix.runs-on.name }})
    runs-on: ${{ matrix.runs-on.label }}
    strategy:
      matrix:
        runs-on:
          - label: lynx-ubuntu-24.04-xlarge
            name: Ubuntu
          # - label: lynx-windows-2022-large
          #   name: Windows
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
        with:
          cache-key: test-${{ runner.os }}
      - name: Install llvm-cov and nextest
        uses: taiki-e/install-action@9ca1734d8940023f074414ee621fd530c4ce10f2 # v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Test
        env:
          CARGO_LLVM_COV_FLAGS_NO_RUNNER: --no-sparse
        run: |
          cargo llvm-cov nextest --profile ci --config-file .cargo/nextest.toml --lcov --output-path lcov.info  --release
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/test-report.junit.xml

  rustfmt:
    runs-on: lynx-ubuntu-24.04-medium
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
        with:
          components: rustfmt
          cache: false
      - name: Format
        run: cargo fmt --check
