name: Rust

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

# Set minimum permissions to prevent unnecessary access
permissions: {}

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: lynx-ubuntu-24.04-xlarge
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1
        with:
          cache-key: test-${{ runner.os }}
      - name: Install llvm-cov and nextest
        uses: taiki-e/install-action@6c6479b49816fcc0975a31af977bdc1f847c2920 # v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Test
        run: |
          export CARGO_LLVM_COV_FLAGS_NO_RUNNER='--no-sparse'
          cargo llvm-cov nextest --profile ci --config-file .cargo/nextest.toml --lcov --output-path lcov.info  --release
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/test-report.junit.xml

  rustfmt:
    runs-on: lynx-ubuntu-24.04-medium
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1
        with:
          components: rustfmt
          cache-key: test-${{ runner.os }}
      - name: Format
        run: cargo fmt --check
